name: Auto Data extraction
on:
    workflow_dispatch:
    schedule:
      - cron: '35 7 * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  auto_catalog_refresh_script:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: main
    - name: Script launch
      working-directory: ./script
      run: ./retrieveData.sh
    - name: Add & Commit
      uses: EndBug/add-and-commit@v9.1.3
      with:
        add: 'data/dblp_articles.ttl'
        message: 'Automatic data retrieval'
        author_name: 'Pierre Maillot'
        author_email: 'pierre.maillot@inria.fr'
    - name: Add & Commit
      uses: EndBug/add-and-commit@v9.1.3
      with:
        add: 'data/dblp_person.ttl'
        message: 'Automatic data retrieval'
        author_name: 'Pierre Maillot'
        author_email: 'pierre.maillot@inria.fr'
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: deploy
